#ifndef FE_GLINFO_H
#define FE_GLINFO_H

#define FE_OPENGL_CORE_PROFILE          0x00032001
#define FE_OPENGL_COMPAT_PROFILE        0x00032002

#define FE_OPENGL_VERSION_MAJOR         3
#define FE_OPENGL_VERSION_MINOR         3
#define FE_OPENGL_PROFILE               FE_OPENGL_CORE_PROFILE

#define FE_GLFW_DEFAULT_WINDOW_LENGTH   600 
#define FE_GLFW_DEFAULT_WINDOW_HEIGHT   400 
#define FE_GLFW_DEFAULT_WINDOW_TITLE    "Framework Engine"
#define FE_GLFW_CURRENT_MONITOR         NULL 
#define FE_GLFW_NO_CONTEXT_SHARE        NULL 

#endif 
