#ifndef FE_GLINFO_H
#define FE_GLINFO_H

#define FE_OPENGL_CORE_PROFILE      0x00032001
#define FE_OPENGL_COMPAT_PROFILE    0x00032002

#define FE_OPENGL_VERSION_MAJOR     3
#define FE_OPENGL_VERSION_MINOR     3
#define FE_OPENGL_PROFILE           FE_OPENGL_CORE_PROFILE

#endif 
